[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/storybook/*"
  to = "/storybook/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
